### ISSUE TITLE
About code style

### ISSUE THREAD

**Issue by xiaozhikang0916** [andanteyk/ElectronicObserver#87]
After modifying code, i always found that it's a big commit with too much unnecessary line changed, especially if i change any form designing. It may be a big problem for code reviewing.
i notice that similar issue has been discussed in #76 , so i wander which kind of line ending do you use in this project.
FYI visual studio uses CRLF as default and hard to change it.

Also i notice that you use tab as indentation, but i'm using 4 spaces. So i want to confirm which kind do you prefer.

And when i change the form designing  in visual studio, it change the `.design.cs` file automatically, but bring a big change to this file. do you have any idea to avoid it?

**Comment by andanteyk** [comment]
#### 改行コード

リポジトリ上では LF に統一してあります。 (#76 で修正されました)
しかし、ローカルのファイルは CRLF で扱っています - git が自動で変換してくれるためです。
`git config core.autocrlf` の結果が `true` の状態で pull / commit すると自動変換されるはずです。

#### インデント

tab で統一してあります。できれば tab で送信していただけると助かります。

#### Form.Designer.cs の変更について

自動生成であるため仕方ないものだと思って、私はそのままコミットしています。
何か良い方法があれば教えてください…

**Comment by RadarNyan** [comment]
**Indent**

What I've been doing so far is to follow code blocks nearby my code. This way I keep my commits minimal and clear and have my code align to nearby original code in all editors (since not every editor has fixed width tabs, and there's no absolute standard for how many spaces should a fixed width tab equal to) I think I'll keep my current behavior for now (see last section also).

**VS reformatting Form.Designer.cs**

I have no idea how to avoid this, it seems to be impossible. So far I haven't tried to make great changes to designer.cs files so I just avoid using Visual Studio Designer, I use text editor to do the editing manually. In fact I barely use Visual Studio to edit anything because I could end up with a huge amount of modification which I'm not intented to. I only use it for building and debugging for now.

**My thought: a styling guideline is needed**

I do think there should be some sort of guideline for contributors to follow, else you **will** end up with a project with mixed coding style. Once a guideline is created and made public, I think you should just make a big commit to change nothing but the code style across all the files (well, also remove some unnecessary lines like "using ElectronicObserver.Utility", VS can do that automatically. By "nothing" I mean "nothing related to a feature change").

*Make it a PR instead of a direct commit* so people can review it and fix any mistake before merging. From that point on, new codes comming in should follow the guideline and the chaos of coding style should be resolved. You should take time, come up with a proper guideline, and then continue the process only if we're not in the middle of the up coming Fall 2016 Event - nobody likes the browser to break during a game event.

**Comment by xiaozhikang0916** [comment]
So i need to change my indent setting to tab and set `core.autocrlf` as true.

> In fact I barely use Visual Studio to edit anything because I could end up with a huge amount of modification which I'm not intented to.

Agreed. Visual Studio helps you formatting the code automatically, but the settings are different from others', this is going to be a disaster.
Using VS Code or other editor may help but they are weak in auto completion.

> A styling guideline is needed

That's true. A guideline can help codes from different contributors keep in uniformed style. Maybe we can start from sharing the style settings ( e.g. indent, line changing, line ending).

> Make it a PR instead of a direct commit

Do you mean that even the project owner should open a PR if he wants to commit to develop branch?
It's a good way for co-operating. But it's a personal repository and it's a problem whether there are enough people and time to review the code.
